taskr/dashboard/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'dashboard'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

taskr/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

taskr/taskr/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^activity-log/', include('activity_log.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', include('home.urls'))
]

taskr/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

taskr/tasks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from jobs.models import Job


class Task(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=255, blank=True, default="", null=True)
    date = models.DateField(default=timezone.now)
    start = models.TimeField(default=timezone.now)
    end = models.TimeField(default=timezone.now)
    notes = models.CharField(max_length=255, blank=True, default="", null=True)

    def save(self, *args, **kwargs):
        """On save, set task title"""
        if len(self.title) == 0:
            self.title = "Task {0}".format(timezone.now().strftime('%H%M%S'))

        return super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

taskr/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model


User = get_user_model()


@login_required(login_url='accounts:login')
def index(request):
    context = {
        'jobs': User.objects.get(username=request.user.username).job_set.order_by('-modified'),
    }
    return render(request, 'dashboard/dashboard.html', context)

taskr/templates/dashboard/add-task-modal.html
<!-- Centered Add Task Modal -->
<div class="modal fade" id="task-modal" tabindex="-1" role="dialog" aria-labelledby="task-modalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="header px-3 py-2">
        <p class="h4 text-center mb-4">Add Task to <strong id="project-name"></strong>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      </div>
      <div class="modal-body">
        <span id="add-task-form-error"></span>
        <form id="add-task-form" action="{% url 'dashboard:tasks:add_task' %}" method="post">
          {% csrf_token %}
          <input type="hidden" id="job-id" name="job-id" value="">
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label for="task-title">Title</label>
                <input type="email" class="form-control" id="task-title" name="task-title" placeholder="e.g. Wednesday Task">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label for="task-date">Date *</label>
                <input type="date" class="form-control" id="task-date" name="task-date" required />
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="task-start">Start *</label>
                <input type="time" class="form-control" id="task-start" name="task-start" required />
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <label for="task-end">End *</label>
                <input type="time" class="form-control" id="task-end" name="task-end" required />
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label for="task-notes">Notes</label>
                <textarea class="form-control" id="task-notes" name="task-notes"></textarea>
              </div>
            </div>
          </div>
          <button type="button" class="btn btn-primary btn-block" onclick="validateTaskForm();">Submit</button>
          <p class="my-4 text-muted text-center">Fields with * are required</p>
        </form>
      </div>
    </div>
  </div>
</div>

taskr/templates/dashboard/alerts.html
{% if messages %}
  {% for message in messages %}
    {% ifequal message.tags "login_success success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-home" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "added_job success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-plus" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "deleted_job success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-trash" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "added_task success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-plus" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "deleted_task success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-trash" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "edited_job success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-pencil" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
    {% ifequal message.tags "edited_task success" %}
      <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong><i class="fa fa-pencil" aria-hidden="true"></i></strong> {{ message|safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endifequal %}
  {% endfor %}
{% endif %}

taskr/templates/dashboard/dashboard.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'global/head.html' %}

    <title>taskr: Dashboard</title>
  </head>
  <body>
    {% include 'global/logged-in-navbar.html' %}

    {% include 'dashboard/jobs-list.html' %}

    {% include 'dashboard/add-task-modal.html' %}

    <!-- Modal Delete Job Confirmation -->
    <div class="modal fade" id="delete-job-modal" tabindex="-1" role="dialog" aria-labelledby="delete-job-modalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="delete-job-modalLabel">Confirm Job Deletion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p class="lead">Are you sure you want to delete <strong id="job-name"></strong>?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <form action='{% url 'dashboard:jobs:delete_job' %}' method='post'>
              {% csrf_token %}
              <input type='hidden' id="job-to-delete-id" name='job-to-delete-id' />
              <button type='submit' class='btn btn-success'>Yes, delete.</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Centered Edit Job Modal -->
    <div class="modal fade" id="edit-job-modal" tabindex="-1" role="dialog" aria-labelledby="edit-job-modalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="header px-3 py-2">
            <p class="h4 text-center mb-4">Edit Job <strong id="edit-project-name"></strong>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </p>
          </div>
          <div class="modal-body">
            <form id="edit-job-form" action="{% url 'dashboard:jobs:edit_job' %}" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="edit-job-title">Title *</label>
                    <input type="text" class="form-control" id="edit-job-title" name="job-title" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="edit-job-date">Date</label>
                    <input type="date" class="form-control" id="edit-job-date" name="job-date">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="edit-job-description">Description</label>
                    <textarea class="form-control" id="edit-job-description" name="job-description"></textarea>
                  </div>
                </div>
              </div>
              <input type="hidden" id="edit-job-id" name="job-id" value="">
              <button type="submit" class="btn btn-primary btn-block">Update Job</button>
              <p class="my-4 text-muted text-center">Fields with * are required</p>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Centered Add Job Modal -->
    <div class="modal fade" id="job-modal" tabindex="-1" role="dialog" aria-labelledby="job-modalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="header px-3 py-2">
            <p class="h4 text-center mb-4">Add Job<strong id="project-name"></strong>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </p>
          </div>
          <div class="modal-body">
            <form id="add-job-form" action="{% url 'dashboard:jobs:add_job' %}" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-title">Title *</label>
                    <input type="text" class="form-control" id="job-title" name="job-title" placeholder="e.g. My Photography Job" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-date">Date</label>
                    <input type="date" class="form-control" id="job-date" name="job-date">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-description">Description</label>
                    <textarea class="form-control" id="job-description" name="job-description"></textarea>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Add Job</button>
              <p class="my-4 text-muted text-center">Fields with * are required</p>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <!-- Local JS -->
    <script type="text/javascript">
      $(document).ready(function(){
        $('.btn.btn-link.ellipsis').popover({
          html:true,
        });


      });

      function searchFocus(element) {
        $(element).removeClass('bg-dark');
        $(element).css('width', '400px !important')

      }
      function searchBlur(element) {
        $(element).addClass('bg-dark');
      }

      function setTaskModalParams(title, job_id) {
        $('#project-name').text(title);
        $('#job-id').val(job_id);
      }

      function setJobModalParams() {
        let date = new Date();
        let mm, dd, yyyy, full_date;

        mm = date.getMonth() + 1;
        dd = date.getDate();
        yyyy = date.getFullYear();

        if (mm < 10) {
          mm = '0' + mm;
        }
        if (dd < 10) {
          dd = '0' + dd;
        }
        full_date = `${yyyy}-${mm}-${dd}`;

        console.log(full_date);
        $('#job-date').val(full_date);
      }

      function validateTaskForm() {
        let task_date = $('#task-date').val();
        let start = $('#task-start').val();
        let end = $('#task-end').val();
        let code = `<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
          <strong><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></strong> Date, Start, and End are required arguments!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>`;

        if (task_date.length > 0 && start.length > 0 && end.length > 0) {
          console.log("Can submit");
          $('#add-task-form').submit();
        } else {
          console.log("Cannot submit");
          $('#add-task-form-error').append(code);
        }
      }

      function setJobToDelete(job_name, job_id) {
        $('#job-to-delete-id').val(job_id);
        $('#job-name').text(job_name);
      }

      function setJobToEdit(job_name, job_id, job_date, job_description) {
        console.log(job_date)
        $('#edit-job-id').val(job_id);
        $('#edit-project-name').text(job_name);
        $('#edit-job-title').val(job_name);
        $('#edit-job-date').val(job_date);
        $('#edit-job-description').val(job_description);
      }

      function validateJobForm() {
        let job_title = $('#job-title').val();

        let code = `<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
          <strong><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></strong> A job title is required!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>`;

        if (job_title.length) {
          console.log("Can submit");
          $('#add-job-form').submit();
        } else {
          console.log("Cannot submit");
          $('#add-job-form-error').append(code);
        }
      }
    </script>
  </body>
</html>

taskr/templates/dashboard/jobs-list.html
<div class="container my-4">
  {% include 'dashboard/alerts.html' %}

  {% if jobs|length > 0 %}
    <button class="btn btn-dark btn-block mb-2" data-toggle="modal" data-target="#job-modal" onclick="setJobModalParams();"><i class="fa fa-plus" aria-hidden="true"></i> Add Job</button>
    {% for job in jobs %}
      <div class="card my-4 {% if forloop.counter0|divisibleby:'2' %}border-focus{% endif %}">
        <div class="card-body">
          {% with job.task_set.all|length as ntasks %}
            <!-- JOB MENU -->
            <span class="pull-right">
              <div class="dropdown show">
                <a class="btn btn-link ellipsis" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="dropdownMenuLink">
                  <button class="btn btn-dark w-75 my-1" data-toggle="modal" data-target="#edit-job-modal" onclick="setJobToEdit('{{ job.title }}', {{ job.pk }}, '{{ job.created|date:"Y-m-d"  }}', '{{ job.description }}');">Edit <i class="fa fa-pencil" aria-hidden="true"></i></button>
                  <button class='btn btn-danger w-75 my-1' data-toggle="modal" data-target="#delete-job-modal" onclick="setJobToDelete('{{ job.title }}', {{ job.pk }});">Delete <i class='fa fa-trash' aria-hidden='true'></i></button>
                </div>
              </div>
            </span>
            <!-- END JOB MENU -->

            <!-- JOB TITLE, NUMBER OF TASKS, CREATION DATE, AND DESCRIPTION -- >
            <h4 class="card-title">
              {{ job.title }}
              <small class="text-muted">
                &middot; {{ ntasks }} {% if ntasks == 1%}task{% else %}tasks{% endif %} &middot; {{ job.created|date:"F d, Y" }}
              </small>
            </h4>
            <p class="card-text lead">{{ job.description }}</p>
            <!-- END JOB TITLE... -->

            <!-- IF THERE ARE TASKS TO VIEW -->
            {% if  ntasks > 0 %}
              <p class="lead text-center text-muted">Showing most recent task</p>
              <table class="table table-sm my-4 text-center">
                <thead>
                  <tr class="text-muted">
                    <td scope="col">Title</td>
                    <td scope="col">Date</td>
                    <td scope="col">Start</td>
                    <td scope="col">End</td>
                    <td scope="col">Notes</td>
                  </tr>
                </thead>
                <tbody>
                  {% with job.task_set.all.last as task %}
                  <tr>
                    <td>{{ task.title }}</td>
                    <td>{{ task.date|date:"m/d/y" }}</td>
                    <td>{{ task.start|time:"g:i A"|lower }}</td>
                    <td>{{ task.end|time:"g:i A"|lower }}</td>
                    <td>{% if task.notes|length == 0 %}<i class="fa fa-ban text-muted" aria-hidden="true"></i>{% else %}<em>{{ task.notes|truncatewords:10 }}</em>{% endif %}</td>
                  </tr>
                  {% endwith %}
                </tbody>
              </table>

              <!-- ADD TASK AND VIEW JOB BUTTONS -->
              <div class="row">
                <div class="col-sm-6">
                  <button class="btn btn-outline-dark btn-block mb-2" data-toggle="modal" data-target="#task-modal" onclick="setTaskModalParams('{{ job.title }}', {{ job.pk }});"><i class="fa fa-plus" aria-hidden="true"></i> Add Task</button>
                </div>
                <div class="col-sm-6">
                  <a href="{% url 'dashboard:jobs:show_job' job_id=job.pk %}" class="btn btn-outline-primary btn-block mb-2"><i class="fa fa-eye" aria-hidden="true"></i> View Job</a>
                </div>
              </div>
              <!-- END ADD TASK AND VIEW JOB BUTTONS -->

            {% else %}
              <p class="text-center text-muted lead my-4">There are no tasks yet.</p>
              <div class="row">
                <div class="col-sm-6">
                  <button class="btn btn-outline-dark btn-block mb-2" data-toggle="modal" data-target="#task-modal" onclick="setTaskModalParams('{{ job.title }}', {{ job.pk }});"><i class="fa fa-plus" aria-hidden="true"></i> Add Task</button>
                </div>
                <div class="col-sm-6">
                  <a href="{% url 'dashboard:jobs:show_job' job_id=job.pk %}" class="btn btn-outline-primary btn-block mb-2"><i class="fa fa-eye" aria-hidden="true"></i> View Job</a>
                </div>
              </div>
            {% endif %}
          {% endwith %}
        </div>
      </div>
    {% endfor %}
  {% else %}
  <div class="section empty">
    <h1 class="display-4 text-center text-muted">You have no Jobs at the moment.</h1>
    <p class="ml-auto mr-auto my-4">
      <button class="btn btn-dark btn-block mb-2" data-toggle="modal" data-target="#job-modal" onclick="setJobModalParams();"><i class="fa fa-plus" aria-hidden="true"></i> Add Job</button>
    </p>
  </div>
  {% endif %}
</div>