taskr/accounts/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register_view, name='register'),
]

taskr/activity_log/urls.py
from django.conf.urls import url
from . import views

app_name = 'activity_log'


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

taskr/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

taskr/taskr/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^activity-log/', include('activity_log.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', include('home.urls'))
]

taskr/templates/global/head.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

<!-- Local CSS  -->
<link rel="stylesheet" href="{% static 'global/css/style.css' %}">

<!-- Font Awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<!-- Favicon -->
<link rel="shortcut icon" href="{% static 'global/img/taskr logo favicon.png' %}">

taskr/templates/global/home-navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand ml-3" href="{% url 'home:index' %}">
    <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <button class="btn btn-link mx-1 my-1">About</button>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:login' %}" class="btn btn-link mx-1 my-1">Sign in <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:register' %}" class="btn btn-link mx-1 my-1"><strong>Sign up</strong></a>
      </li>
    </ul>
  </div>
</nav>

taskr/templates/global/logged-in-navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <a class="navbar-brand" href="{% url 'home:index' %}">
    <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav text-center mr-0 ml-auto">
      <li class="nav-item dropdown mx-1 my-1">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user" aria-hidden="true"></i> Welcome, {% if request.user.first_name %}{{ request.user.first_name }} {{ request.user.last_name }}{% else %}{{ request.user.username }}{% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><i class="fa fa-cog text-muted"></i> Settings</a>
          <a class="dropdown-item" href="{% url 'activity_log:index' %}"><i class="fa fa-line-chart text-muted"></i> Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-power-off text-muted"></i> Sign Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

taskr/templates/global/login-modal.html
<!-- Centered Sign In Modal -->
<div class="modal fade" id="sign-in-modal" tabindex="-1" role="dialog" aria-labelledby="sign-in-modalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="header px-3 py-2">
        <p class="h4 text-center mb-4">Sign In
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      </div>
      <div class="modal-body text-center">
        <div class="social-login">
          <button type="button" class="btn btn-outline-secondary btn-block"><i class="fa fa-google" aria-hidden="true"></i> Sign In with Google Account</button>
          <button type="button" class="btn btn-outline-primary btn-block"><i class="fa fa-facebook-square" aria-hidden="true"></i> Sign In with Facebook Account</button>
        </div>

        <hr class="style-eight my-4">
        <form action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username" aria-label="Username" required>
          </div>
          <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" aria-label="Password" required>
          </div>          
          <button type="submit" class="btn btn-primary btn-block">Sign In</button>
        </form>
        <p class="lead my-4 text-muted">Don't have an account? <a href="#" data-toggle="modal" data-target="#sign-up-modal" data-dismiss="modal" class="sign-up-link">Sign Up</a></p>
      </div>
    </div>
  </div>
</div>

taskr/templates/global/login-navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand ml-3" href="{% url 'home:index' %}">
    <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <button class="btn btn-link mx-1 my-1">About</button>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:register' %}" class="btn btn-link mx-1 my-1"><strong>Sign up</strong></a>
      </li>
    </ul>
  </div>
</nav>

taskr/templates/global/register-modal.html
<!-- Centered Sign Up Modal -->
<div class="modal fade" id="sign-up-modal" tabindex="-1" role="dialog" aria-labelledby="sign-up-modalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="header px-3 py-2">
        <p class="h4 text-center mb-4">Sign Up
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      </div>
      <div class="modal-body text-center">
        <div class="social-login">
          <button type="button" class="btn btn-outline-secondary btn-block"><i class="fa fa-google" aria-hidden="true"></i> Sign Up with Google Account</button>
          <button type="button" class="btn btn-outline-primary btn-block"><i class="fa fa-facebook-square" aria-hidden="true"></i> Sign Up with Facebook Account</button>
        </div>
        <hr class="style-eight my-4">
        <form class="" action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <input type="text" class="form-control" id="username" name="username" placeholder="Username *">
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First name">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last name">
              </div>
            </div>
          </div>
          <div class="form-group">
            <input type="email" class="form-control" id="email" name="email" placeholder="Email *">
          </div>

          <div class="form-group">
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Password *">
          </div>
          <div class="form-group">
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password *">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Sign In</button>
        </form>
        <p class="lead my-4 text-muted">Already have an account? <a href="#" data-toggle="modal" data-target="#sign-in-modal" data-dismiss="modal" class="sign-up-link">Sign In</a></p>
        <p class="my-4 text-muted text-center">Fields with * are required</p>
      </div>
    </div>
  </div>
</div>

taskr/templates/global/register-navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand ml-3" href="{% url 'home:index' %}">
    <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <button class="btn btn-link mx-1 my-1">About</button>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:login' %}" class="btn btn-link mx-1 my-1"><strong>Sign in</strong></a>
      </li>
    </ul>
  </div>
</nav>