taskr/accounts/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register_view, name='register'),
]

taskr/activity_log/urls.py
from django.conf.urls import url
from . import views

app_name = 'activity_log'


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

taskr/dashboard/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'dashboard'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

taskr/home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

taskr/taskr/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^activity-log/', include('activity_log.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', include('home.urls'))
]

taskr/activity_log/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


User = get_user_model()


class Activity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, default='<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>')
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "Activity {0} - {1}".format(self.pk, self.description)

taskr/activity_log/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from models import Activity
from django.contrib.auth import get_user_model


User = get_user_model()


def index(request):
    context = {
        'activities': User.objects.get(username=request.user.username).activity_set.order_by('-created')
    }
    return render(request, 'activity_log/activity_log.html', context)

taskr/templates/activity_log/activity_log.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'global/head.html' %}

    <title>taskr: My Activity</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'dashboard:index' %}">
          <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
        </a>
      {% else %}
        <a class="navbar-brand" href="{% url 'home:index' %}">
          <img src="{% static 'global/img/taskr logo.png' %}" alt=""> taskr
        </a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
          <ul class="navbar-nav ml-auto mr-auto">
            <form class="form-inline mx-1 my-1">
              <div class="input-group">
                <input type="text" onfocus="searchFocus(this);" onblur="searchBlur(this);" class="form-control bg-dark" placeholder="e.g. webdev, tutoring..." aria-label="Username" aria-describedby="basic-addon1">
                <div class="input-group-append">
                  <button type="button" class="btn btn-light"><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
              </div>
            </form>
          </ul>
        {% endif %}
        <ul class="navbar-nav text-center">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown mx-1 my-1">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user" aria-hidden="true"></i> Welcome, {% if request.user.first_name %}{{ request.user.first_name }} {{ request.user.last_name }}{% else %}{{ request.user.username }}{% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#"><i class="fa fa-cog text-muted"></i> Settings</a>
                <a class="dropdown-item" href="{% url 'activity_log:index' %}"><i class="fa fa-line-chart text-muted"></i> Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-power-off text-muted"></i> Sign Out</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item active">
              <button class="btn btn-outline-light mx-1 my-1" data-toggle="modal" data-target="#task-modal">Sign in <span class="sr-only">(current)</span></button>
            </li>
            <li class="nav-item">
              <button class="btn btn-link mx-1 my-1" type="button" name="button">Sign up</button>
            </li>
          {% endif %}
        </ul>
      </div>
      {# </div> #}
    </nav>
    <div class="container my-4">
      {% if messages %}
        {% for message in messages %}
          {% ifequal message.tags "login_success success" %}
            <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
              <strong><i class="fa fa-home" aria-hidden="true"></i></strong> {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endifequal %}
        {% endfor %}
      {% endif %}
      <h1 class="display-4 text-center">My Activity</h1>

      {% if activities|length > 0 %}
        {% for activity in activities %}
        <div class="card my-4 {% if forloop.counter0|divisibleby:'2' %}border-focus{% endif %}">
          <div class="card-body">
            <div class="row text-center">
              <div class="col-sm-1">
                <h4 class="card-title">{{ activity.icon|safe }}</h4>
              </div>
              <div class="col-sm-4">
                <h4 class="card-title">{{ activity.created|date:"F d, Y"}} {{ activity.created|time:"g:i A"|lower }}</h4>
              </div>
              <div class="col-sm-7">
                <p class="card-text lead">{{ activity.description|safe }}</p>
              </div>
            </div>

          </div>
        </div>
        {% endfor %}
      {% else %}
      <h1 class="display-4 text-center text-muted">You have no recent activity.</h1>
      <p class="w-50 ml-auto mr-auto my-4">
        <button class="btn btn-outline-dark btn-block mb-2" data-toggle="modal" data-target="#job-modal" onclick="setJobModalParams();"><i class="fa fa-plus" aria-hidden="true"></i> Add Job</button>
      </p>
      {% endif %}
    </div>

    <!-- Centered Add Task Modal -->
    <div class="modal fade" id="task-modal" tabindex="-1" role="dialog" aria-labelledby="task-modalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="header px-3 py-2">
            <p class="h4 text-center mb-4">Add Task to <strong id="project-name"></strong>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </p>
          </div>
          <div class="modal-body">
            <span id="add-task-form-error"></span>
            <form id="add-task-form" action="{% url 'dashboard:tasks:add_task' %}" method="post">
              {% csrf_token %}
              <input type="hidden" id="job-id" name="job-id" value="">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="task-title">Title</label>
                    <input type="email" class="form-control" id="task-title" name="task-title" placeholder="e.g. Wednesday Task">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="task-date">Date *</label>
                    <input type="date" class="form-control" id="task-date" name="task-date" required />
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="task-start">Start *</label>
                    <input type="time" class="form-control" id="task-start" name="task-start" required />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="task-end">End *</label>
                    <input type="time" class="form-control" id="task-end" name="task-end" required />
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="task-notes">Notes</label>
                    <textarea class="form-control" id="task-notes" name="task-notes"></textarea>
                  </div>
                </div>
              </div>
              <button type="button" class="btn btn-primary btn-block" onclick="validateTaskForm();">Submit</button>
              <p class="my-4 text-muted text-center">Fields with * are required</p>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Centered Add Job Modal -->
    <div class="modal fade" id="job-modal" tabindex="-1" role="dialog" aria-labelledby="job-modalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="header px-3 py-2">
            <p class="h4 text-center mb-4">Add Job<strong id="project-name"></strong>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </p>
          </div>
          <div class="modal-body">
            <form id="add-job-form" action="{% url 'dashboard:jobs:add_job' %}" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-title">Title *</label>
                    <input type="text" class="form-control" id="job-title" name="job-title" placeholder="e.g. My Photography Job" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-date">Date</label>
                    <input type="date" class="form-control" id="job-date" name="job-date">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="job-description">Description</label>
                    <textarea class="form-control" id="job-description" name="job-description"></textarea>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Add Job</button>
              <p class="my-4 text-muted text-center">Fields with * are required</p>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <!-- Local JS -->
    <script type="text/javascript">
      $(document).ready(function(){



      });

      function searchFocus(element) {
        $(element).removeClass('bg-dark');
        $(element).css('width', '400px !important')

      }
      function searchBlur(element) {
        $(element).addClass('bg-dark');
      }

      function setTaskModalParams(title, job_id) {
        console.log(job_id);
        $('#project-name').text(title);
        $('#job-id').val(job_id);

        console.log($('#job-id').val());
      }

      function setJobModalParams() {
        let date = new Date();
        let mm, dd, yyyy, full_date;

        mm = date.getMonth() + 1;
        dd = date.getDate();
        yyyy = date.getFullYear();

        if (mm < 10) {
          mm = '0' + mm;
        }
        if (dd < 10) {
          dd = '0' + dd;
        }
        full_date = `${yyyy}-${mm}-${dd}`;

        console.log(full_date);
        $('#job-date').val(full_date);
      }

      function validateTaskForm() {
        let task_date = $('#task-date').val();
        let start = $('#task-start').val();
        let end = $('#task-end').val();
        let code = `<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
          <strong><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></strong> Date, Start, and End are required arguments!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>`;

        if (task_date.length > 0 && start.length > 0 && end.length > 0) {
          console.log("Can submit");
          $('#add-task-form').submit();
        } else {
          console.log("Cannot submit");
          $('#add-task-form-error').append(code);
        }
      }

      function validateJobForm() {
        let job_title = $('#job-title').val();

        let code = `<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
          <strong><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></strong> A job title is required!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>`;

        if (job_title.length) {
          console.log("Can submit");
          $('#add-job-form').submit();
        } else {
          console.log("Cannot submit");
          $('#add-job-form-error').append(code);
        }
      }
    </script>
  </body>
</html>